- type: entity
  name: borg's stun baton
  parent: Stunbaton
  id: StunbatonBorg
  description: A stun baton for incapacitating people with. Actively harming with this is considered bad tone.
  components:
  - type: BatterySelfRecharger
    autoRecharge: true
    autoRechargeRate: 20

- type: entity
  name: borg's disabler
  parent: WeaponDisabler
  id: WeaponDisablerBorg
  description: A stun baton for incapacitating people with. Actively harming with this is considered bad tone.
  components:
  - type: BatterySelfRecharger
    autoRecharge: true
    autoRechargeRate: 20

- type: entity
  name: borg's disabler
  parent: WeaponAntiqueLaser
  id: WeaponLaserBorg
  description: Bzzt.
  components:
  - type: BatterySelfRecharger
    autoRecharge: true
    autoRechargeRate: 40
  - type: HitscanBatteryAmmoProvider
    proto: RedMediumLaser
    fireCost: 200