using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;

namespace Content.Client.Economy.ATM.UI
{
    [GenerateTypedNameReferences]
    public sealed partial class ATMMenu : DefaultWindow
    {
        [Dependency] private readonly IPrototypeManager _prototypeManager = default!;

        public ATMMenu()
        {
            MinSize = (250, 150);
            SetSize = (450, 150);
            RobustXamlLoader.Load(this);
            IoCManager.InjectDependencies(this);
        }
    }
}
