using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;
using static Content.Shared.Economy.ATM.SharedATMComponent;

namespace Content.Client.Economy.ATM.UI
{
    [GenerateTypedNameReferences]
    public sealed partial class ATMMenu : DefaultWindow
    {
        // [Dependency] private readonly IPrototypeManager _prototypeManager = default!;

        public ATMMenu()
        {
            // MinSize = (250, 150);
            // SetSize = (450, 150);
            RobustXamlLoader.Load(this);
            // IoCManager.InjectDependencies(this);
        }
        public void UpdateState(ATMBoundUserInterfaceState state)
        {
            ShowWithdraw.Visible = state.IsCardPresent;
        }
    }
}
