using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using static Content.Shared.Economy.ATM.SharedATMComponent;

namespace Content.Client.Economy.ATM.UI
{
    [GenerateTypedNameReferences]
    public sealed partial class ATMMenu : DefaultWindow
    {
        // [Dependency] private readonly IPrototypeManager _prototypeManager = default!;

        public ATMMenu()
        {
            // MinSize = (250, 150);
            // SetSize = (450, 150);
            RobustXamlLoader.Load(this);
            // IoCManager.InjectDependencies(this);
        }
        public void UpdateState(ATMBoundUserInterfaceState state)
        {
            WelcomeLabel.Text = state.IdCardFullName != null
                ? Loc.GetString("atm-ui-welcome-label-w-name", ("name", state.IdCardFullName))
                : Loc.GetString("atm-ui-default-welcome-label");
            IdCardButton.Text = state.IdCardEntityName != null
                ? state.IdCardEntityName
                : Loc.GetString("atm-ui-no-card-label");
            AccountBalance.Text = state.BankAccountBalance != null
                ? Loc.GetString("atm-ui-account-balance", ("balance", state.BankAccountBalance))
                : Loc.GetString("atm-ui-account-balance", ("balance", "%ERR!"));
            ErrorLabel.Visible = state.IsCardPresent && !state.HaveAccessToBankAccount;
            ShowWithdraw.Visible = state.IsCardPresent && state.HaveAccessToBankAccount;
        }
    }
}
