- type: job
  id: SecurityBorg
  name: job-name-securityborg
  playTimeTracker: JobBorg
  requirements:
    - !type:DepartmentTimeRequirement
      department: Security
      time: 12000
  supervisors: job-supervisors-ai
  startingGear: BorgGear
  weight: 20
  icon: "AI"
  canBeAntag: false
  jobEntity: secborg

- type: startingGear
  id: BorgGear
  equipment:
    shoes: ClothingShoesColorBlack # Corvax-Resprite
    outerClothing: ClothingOuterCardborg
    head: ClothingHeadHatCardborg
    id: BorgsPDA
    jumpsuit: ClothingUniformJumpsuitColorWhite